{
    'name': 'Gestión de Pesajes POS Fleet',
    'version': '19.0.1.0.0',
    'summary': 'Interfaz POS ligera para pesajes de camiones con integración Fleet e Inventario',
    'author': 'Balanza',
    'category': 'Operations/Inventory',
    'depends': ['fleet', 'stock', 'hr', 'product', 'base_setup'],
    'data': [
        'security/ir.model.access.csv',
        'data/pesaje_state_data.xml',
        'views/pesaje_substate_views.xml',
        'views/pesaje_campo_views.xml',
        'views/pesaje_hibrido_views.xml',
        'views/pesaje_views.xml',
        'wizards/pesaje_cancelar_views.xml',
        'wizards/report_pesaje_wizard_views.xml',
        # 'views/res_config_settings_views.xml',  # TODO: ajustar a sintaxis Odoo 19
        'views/pesaje_pos_action.xml',
        'views/menus.xml',
        'report/pesaje_report_actions.xml',
        'report/pesaje_ticket.xml',
        'report/pesaje_report_diario.xml',
        'report/pesaje_report_vehiculo.xml',
        'report/pesaje_report_descarte.xml',
        'report/pesaje_report_tiempos.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'pesaje_pos_fleet/static/src/css/pesaje.css',
            'pesaje_pos_fleet/static/src/css/pos_screen.css',
            'pesaje_pos_fleet/static/src/app/services/offline_db.js',
            'pesaje_pos_fleet/static/src/app/services/pesaje_api.js',
            'pesaje_pos_fleet/static/src/app/components/BigButton.js',
            'pesaje_pos_fleet/static/src/app/components/KpiCard.js',
            'pesaje_pos_fleet/static/src/app/components/OfflineBanner.js',
            'pesaje_pos_fleet/static/src/app/components/SyncIndicator.js',
            'pesaje_pos_fleet/static/src/app/components/TruckCard.js',
            'pesaje_pos_fleet/static/src/app/components/SubstateSelector.js',
            'pesaje_pos_fleet/static/src/app/components/WeightModal.js',
            'pesaje_pos_fleet/static/src/app/screens/PinLoginScreen.js',
            'pesaje_pos_fleet/static/src/app/screens/DashboardScreen.js',
            'pesaje_pos_fleet/static/src/app/screens/PesajeFormModal.js',
            'pesaje_pos_fleet/static/src/app/screens/PesajeScreen.js',
            'pesaje_pos_fleet/static/src/app/PosApp.js',
            'pesaje_pos_fleet/static/src/app/main.js',
        ],
    },
    'demo': [
        'demo/demo_data.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
